[package]
name = "indoc-impl"
version = "0.2.4" # remember to update html_root_url
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Indented document literals"
repository = "https://github.com/dtolnay/indoc"
documentation = "https://github.com/dtolnay/indoc"
keywords = ["heredoc", "nowdoc", "multiline", "string", "literal"]

[features]
unstable = []

[lib]
proc-macro = true

[dependencies]
proc-macro-hack = "0.4"
proc-macro2 = { version = "0.3", default-features = false }
quote = { version = "0.5", default-features = false }
syn = { version = "0.13", default-features = false, features = ["derive", "parsing", "printing"] }
unindent = { version = "0.1", path = "../unindent" }
