[package]
name = "indoc-impl"
version = "0.2.0" # remember to update html_root_url
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Indented document literals"
repository = "https://github.com/dtolnay/indoc"
documentation = "https://github.com/dtolnay/indoc"
keywords = ["heredoc", "nowdoc", "multiline", "string", "literal"]

[lib]
proc-macro = true

[dependencies]
proc-macro-hack = "0.3"
quote = "0.3"
syn = "0.11"
unindent = { version = "0.1", path = "../unindent" }
