[package]
name = "indoc"
version = "0.1.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Indented document literals"
repository = "https://github.com/dtolnay/indoc"
keywords = ["heredoc", "nowdoc"]

[lib]
name = "indoc"
plugin = true
