[package]
name = "indoc"
version = "0.1.1"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Indented document literals"
repository = "https://github.com/dtolnay/indoc"
keywords = ["heredoc", "nowdoc"]

[lib]
name = "indoc"
plugin = true

[features]
default = []
with-syntex = ["syntex", "syntex_syntax"]

[dependencies]
syntex = { version = "^0.30", optional = true }
syntex_syntax = { version = "^0.30", optional = true }
