[package]
name = "indoc"
version = "0.1.9"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Indented document literals"
repository = "https://github.com/dtolnay/indoc"
documentation = "https://github.com/dtolnay/indoc"
keywords = ["heredoc", "nowdoc", "multiline", "string", "literal"]

[lib]
name = "indoc"
plugin = true

[features]
default = []
with-syntex = ["syntex", "syntex_syntax"]

[dependencies]
clippy = { version = "^0.*", optional = true }
syntex = { version = "^0.33", optional = true }
syntex_syntax = { version = "^0.33", optional = true }

[dev-dependencies]
compiletest_rs = "^0.1"
